version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  commands:
  - pip install -r docs/requirements.txt
  - sphinx-apidoc -f -o docs/source/api src/lembas -H "API Docs"
  - sphinx-build -b html -d docs/build/doctrees docs/source _readthedocs/html
sphinx:
  configuration: docs/conf.py
