[tool.poetry]
name = "lead-core"
version = "0.1.0.dev0"
description = "Lifecycle Engineering Analysis and Design"
authors = ["Your Name <you@example.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
