[tool.poetry]
name = "lead-core"
version = "0.1.0.dev0"
description = "Lifecycle Engineering Analysis and Design"
authors = [
    "Matt Kramer <mkramer@anaconda.com>",
    "Jose Mesa <jmesa@anaconda.com>",
]
license = "MIT"
packages = [
    { include = "lead", from = "src" },
]

[tool.poetry.dependencies]
python = ">=3.9,<3.11"

# Optional dependencies for examples
pandas = { version = "^1.4.3", optional = true }
planingfsi = { git = "https://github.com/mattkram/planingfsi.git", branch = "dev", optional = true }

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
pytest-cov = "^3.0.0"

[tool.poetry.extras]
examples = ["planingfsi", "pandas"]

[tool.isort]
profile = "black"
force_single_line = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
