[tool.poetry]
name = "lead-core"
version = "0.1.0.dev0"
description = "Lifecycle Engineering Analysis and Design"
authors = [
    "Matt Kramer <mkramer@anaconda.com>",
    "Jose Mesa <jmesa@anaconda.com>",
]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.9,<3.11"

[tool.poetry.dev-dependencies]
mypy = "^0.971"
planingfsi = { git = "https://github.com/mattkram/planingfsi.git", branch = "dev" }

[tool.isort]
profile = "black"
force_single_line = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
