[build-system]
requires = ["setuptools>=42", "setuptools-scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "lembas"
dynamic = ["version"]
description = "Lifecycle Engineering Model-Based Analysis System"
license = { text = "MIT" }
requires-python = ">=3.9"
dependencies = []

[project.optional-dependencies]
dev = [
    "pytest<=7.2",
    "pytest-cov<=3.1",
]
examples = [
    "planingfsi @ git+https://github.com/mattkram/planingfsi.git@main",
    "pandas <= 1.5",
]
ci = ["lembas[dev]"]

[tool.isort]
profile = "black"
force_single_line = true

[tool.setuptools_scm]
write_to = "src/lembas/_version.py"
