name: Run Tests

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11' ]
        include:
        - python-version: '3.12-dev'
          os: ubuntu-latest
          experimental: true
    runs-on: ${{ matrix.os }}
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Set up python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install library
      run: pip install ".[ci]"
    - name: Test with pytest
      run: |
        pytest \
          --junitxml=./test-reports/junit.xml \
          --cov-report xml:./test-reports/coverage.xml \
          --cov lembas \
          --cov tests \
          tests
    - name: Publish code coverage
      uses: codecov/codecov-action@v2
      with:
        files: ./test-reports/coverage.xml
        env_vars: OS,PYTHON
